version: '3.8'

services:
  backend:
    image:  aniket1010/go-backend
    container_name: go-backend
    ports:
      - "8081:8080"
    networks:
      - app_network

  frontend:
    image: aniket1010/static-frontend
    container_name: static-frontend
    ports:
      - "8082:80"
    networks:
      - app_network

  reverse_proxy:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
